name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install
        pip install mypy pytest pytest-cov
    - name: Pytest
      run: |
        pytest --cov=prices --cov=tests
    - uses: codecov/codecov-action@v1
    - name: Linters
      run: |
        pylint prices tests setup.py
        mypy prices --ignore-missing-imports
        black --check .